# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/CoralEdgeTpu

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/CoralEdgeTpu

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/CoralEdgeTpu/CMakeFiles /home/pi/CoralEdgeTpu//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/CoralEdgeTpu/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named detector

# Build rule for target.
detector: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 detector
.PHONY : detector

# fast build rule for target.
detector/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/build
.PHONY : detector/fast

#=============================================================================
# Target rules for targets named config_loader_test

# Build rule for target.
config_loader_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 config_loader_test
.PHONY : config_loader_test

# fast build rule for target.
config_loader_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_loader_test.dir/build.make CMakeFiles/config_loader_test.dir/build
.PHONY : config_loader_test/fast

#=============================================================================
# Target rules for targets named servo_test

# Build rule for target.
servo_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 servo_test
.PHONY : servo_test

# fast build rule for target.
servo_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/servo_test.dir/build.make CMakeFiles/servo_test.dir/build
.PHONY : servo_test/fast

#=============================================================================
# Target rules for targets named dlopen_test

# Build rule for target.
dlopen_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dlopen_test
.PHONY : dlopen_test

# fast build rule for target.
dlopen_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlopen_test.dir/build.make CMakeFiles/dlopen_test.dir/build
.PHONY : dlopen_test/fast

#=============================================================================
# Target rules for targets named test_config

# Build rule for target.
test_config: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_config
.PHONY : test_config

# fast build rule for target.
test_config/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/build
.PHONY : test_config/fast

#=============================================================================
# Target rules for targets named minimal_model_test

# Build rule for target.
minimal_model_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 minimal_model_test
.PHONY : minimal_model_test

# fast build rule for target.
minimal_model_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_model_test.dir/build.make CMakeFiles/minimal_model_test.dir/build
.PHONY : minimal_model_test/fast

#=============================================================================
# Target rules for targets named inspect_model_tensors

# Build rule for target.
inspect_model_tensors: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 inspect_model_tensors
.PHONY : inspect_model_tensors

# fast build rule for target.
inspect_model_tensors/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/inspect_model_tensors.dir/build.make CMakeFiles/inspect_model_tensors.dir/build
.PHONY : inspect_model_tensors/fast

#=============================================================================
# Target rules for targets named test_tensor_access

# Build rule for target.
test_tensor_access: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_tensor_access
.PHONY : test_tensor_access

# fast build rule for target.
test_tensor_access/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tensor_access.dir/build.make CMakeFiles/test_tensor_access.dir/build
.PHONY : test_tensor_access/fast

#=============================================================================
# Target rules for targets named test_ballistics_fix

# Build rule for target.
test_ballistics_fix: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ballistics_fix
.PHONY : test_ballistics_fix

# fast build rule for target.
test_ballistics_fix/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_fix.dir/build.make CMakeFiles/test_ballistics_fix.dir/build
.PHONY : test_ballistics_fix/fast

#=============================================================================
# Target rules for targets named test_ballistics_simple

# Build rule for target.
test_ballistics_simple: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ballistics_simple
.PHONY : test_ballistics_simple

# fast build rule for target.
test_ballistics_simple/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_simple.dir/build.make CMakeFiles/test_ballistics_simple.dir/build
.PHONY : test_ballistics_simple/fast

#=============================================================================
# Target rules for targets named test_ballistics_actual

# Build rule for target.
test_ballistics_actual: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ballistics_actual
.PHONY : test_ballistics_actual

# fast build rule for target.
test_ballistics_actual/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_actual.dir/build.make CMakeFiles/test_ballistics_actual.dir/build
.PHONY : test_ballistics_actual/fast

#=============================================================================
# Target rules for targets named test_ballistics_fixed

# Build rule for target.
test_ballistics_fixed: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ballistics_fixed
.PHONY : test_ballistics_fixed

# fast build rule for target.
test_ballistics_fixed/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_fixed.dir/build.make CMakeFiles/test_ballistics_fixed.dir/build
.PHONY : test_ballistics_fixed/fast

civetweb/src/civetweb.o: civetweb/src/civetweb.c.o
.PHONY : civetweb/src/civetweb.o

# target to build an object file
civetweb/src/civetweb.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/civetweb/src/civetweb.c.o
.PHONY : civetweb/src/civetweb.c.o

civetweb/src/civetweb.i: civetweb/src/civetweb.c.i
.PHONY : civetweb/src/civetweb.i

# target to preprocess a source file
civetweb/src/civetweb.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/civetweb/src/civetweb.c.i
.PHONY : civetweb/src/civetweb.c.i

civetweb/src/civetweb.s: civetweb/src/civetweb.c.s
.PHONY : civetweb/src/civetweb.s

# target to generate assembly for a file
civetweb/src/civetweb.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/civetweb/src/civetweb.c.s
.PHONY : civetweb/src/civetweb.c.s

inspect_model_tensors.o: inspect_model_tensors.cpp.o
.PHONY : inspect_model_tensors.o

# target to build an object file
inspect_model_tensors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/inspect_model_tensors.dir/build.make CMakeFiles/inspect_model_tensors.dir/inspect_model_tensors.cpp.o
.PHONY : inspect_model_tensors.cpp.o

inspect_model_tensors.i: inspect_model_tensors.cpp.i
.PHONY : inspect_model_tensors.i

# target to preprocess a source file
inspect_model_tensors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/inspect_model_tensors.dir/build.make CMakeFiles/inspect_model_tensors.dir/inspect_model_tensors.cpp.i
.PHONY : inspect_model_tensors.cpp.i

inspect_model_tensors.s: inspect_model_tensors.cpp.s
.PHONY : inspect_model_tensors.s

# target to generate assembly for a file
inspect_model_tensors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/inspect_model_tensors.dir/build.make CMakeFiles/inspect_model_tensors.dir/inspect_model_tensors.cpp.s
.PHONY : inspect_model_tensors.cpp.s

minimal_model_test.o: minimal_model_test.cpp.o
.PHONY : minimal_model_test.o

# target to build an object file
minimal_model_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_model_test.dir/build.make CMakeFiles/minimal_model_test.dir/minimal_model_test.cpp.o
.PHONY : minimal_model_test.cpp.o

minimal_model_test.i: minimal_model_test.cpp.i
.PHONY : minimal_model_test.i

# target to preprocess a source file
minimal_model_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_model_test.dir/build.make CMakeFiles/minimal_model_test.dir/minimal_model_test.cpp.i
.PHONY : minimal_model_test.cpp.i

minimal_model_test.s: minimal_model_test.cpp.s
.PHONY : minimal_model_test.s

# target to generate assembly for a file
minimal_model_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal_model_test.dir/build.make CMakeFiles/minimal_model_test.dir/minimal_model_test.cpp.s
.PHONY : minimal_model_test.cpp.s

src/application.o: src/application.cpp.o
.PHONY : src/application.o

# target to build an object file
src/application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/application.cpp.o
.PHONY : src/application.cpp.o

src/application.i: src/application.cpp.i
.PHONY : src/application.i

# target to preprocess a source file
src/application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/application.cpp.i
.PHONY : src/application.cpp.i

src/application.s: src/application.cpp.s
.PHONY : src/application.s

# target to generate assembly for a file
src/application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/application.cpp.s
.PHONY : src/application.cpp.s

src/application_supervisor.o: src/application_supervisor.cpp.o
.PHONY : src/application_supervisor.o

# target to build an object file
src/application_supervisor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/application_supervisor.cpp.o
.PHONY : src/application_supervisor.cpp.o

src/application_supervisor.i: src/application_supervisor.cpp.i
.PHONY : src/application_supervisor.i

# target to preprocess a source file
src/application_supervisor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/application_supervisor.cpp.i
.PHONY : src/application_supervisor.cpp.i

src/application_supervisor.s: src/application_supervisor.cpp.s
.PHONY : src/application_supervisor.s

# target to generate assembly for a file
src/application_supervisor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/application_supervisor.cpp.s
.PHONY : src/application_supervisor.cpp.s

src/camera_capture.o: src/camera_capture.cpp.o
.PHONY : src/camera_capture.o

# target to build an object file
src/camera_capture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/camera_capture.cpp.o
.PHONY : src/camera_capture.cpp.o

src/camera_capture.i: src/camera_capture.cpp.i
.PHONY : src/camera_capture.i

# target to preprocess a source file
src/camera_capture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/camera_capture.cpp.i
.PHONY : src/camera_capture.cpp.i

src/camera_capture.s: src/camera_capture.cpp.s
.PHONY : src/camera_capture.s

# target to generate assembly for a file
src/camera_capture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/camera_capture.cpp.s
.PHONY : src/camera_capture.cpp.s

src/config_loader.o: src/config_loader.cpp.o
.PHONY : src/config_loader.o

# target to build an object file
src/config_loader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/config_loader.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_loader_test.dir/build.make CMakeFiles/config_loader_test.dir/src/config_loader.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/src/config_loader.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_fix.dir/build.make CMakeFiles/test_ballistics_fix.dir/src/config_loader.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_actual.dir/build.make CMakeFiles/test_ballistics_actual.dir/src/config_loader.cpp.o
.PHONY : src/config_loader.cpp.o

src/config_loader.i: src/config_loader.cpp.i
.PHONY : src/config_loader.i

# target to preprocess a source file
src/config_loader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/config_loader.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_loader_test.dir/build.make CMakeFiles/config_loader_test.dir/src/config_loader.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/src/config_loader.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_fix.dir/build.make CMakeFiles/test_ballistics_fix.dir/src/config_loader.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_actual.dir/build.make CMakeFiles/test_ballistics_actual.dir/src/config_loader.cpp.i
.PHONY : src/config_loader.cpp.i

src/config_loader.s: src/config_loader.cpp.s
.PHONY : src/config_loader.s

# target to generate assembly for a file
src/config_loader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/config_loader.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_loader_test.dir/build.make CMakeFiles/config_loader_test.dir/src/config_loader.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/src/config_loader.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_fix.dir/build.make CMakeFiles/test_ballistics_fix.dir/src/config_loader.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_actual.dir/build.make CMakeFiles/test_ballistics_actual.dir/src/config_loader.cpp.s
.PHONY : src/config_loader.cpp.s

src/h264_encoder.o: src/h264_encoder.cpp.o
.PHONY : src/h264_encoder.o

# target to build an object file
src/h264_encoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/h264_encoder.cpp.o
.PHONY : src/h264_encoder.cpp.o

src/h264_encoder.i: src/h264_encoder.cpp.i
.PHONY : src/h264_encoder.i

# target to preprocess a source file
src/h264_encoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/h264_encoder.cpp.i
.PHONY : src/h264_encoder.cpp.i

src/h264_encoder.s: src/h264_encoder.cpp.s
.PHONY : src/h264_encoder.s

# target to generate assembly for a file
src/h264_encoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/h264_encoder.cpp.s
.PHONY : src/h264_encoder.cpp.s

src/image_processor.o: src/image_processor.cpp.o
.PHONY : src/image_processor.o

# target to build an object file
src/image_processor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/image_processor.cpp.o
.PHONY : src/image_processor.cpp.o

src/image_processor.i: src/image_processor.cpp.i
.PHONY : src/image_processor.i

# target to preprocess a source file
src/image_processor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/image_processor.cpp.i
.PHONY : src/image_processor.cpp.i

src/image_processor.s: src/image_processor.cpp.s
.PHONY : src/image_processor.s

# target to generate assembly for a file
src/image_processor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/image_processor.cpp.s
.PHONY : src/image_processor.cpp.s

src/inference.o: src/inference.cpp.o
.PHONY : src/inference.o

# target to build an object file
src/inference.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/inference.cpp.o
.PHONY : src/inference.cpp.o

src/inference.i: src/inference.cpp.i
.PHONY : src/inference.i

# target to preprocess a source file
src/inference.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/inference.cpp.i
.PHONY : src/inference.cpp.i

src/inference.s: src/inference.cpp.s
.PHONY : src/inference.s

# target to generate assembly for a file
src/inference.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/inference.cpp.s
.PHONY : src/inference.cpp.s

src/keyboard_monitor.o: src/keyboard_monitor.cpp.o
.PHONY : src/keyboard_monitor.o

# target to build an object file
src/keyboard_monitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/keyboard_monitor.cpp.o
.PHONY : src/keyboard_monitor.cpp.o

src/keyboard_monitor.i: src/keyboard_monitor.cpp.i
.PHONY : src/keyboard_monitor.i

# target to preprocess a source file
src/keyboard_monitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/keyboard_monitor.cpp.i
.PHONY : src/keyboard_monitor.cpp.i

src/keyboard_monitor.s: src/keyboard_monitor.cpp.s
.PHONY : src/keyboard_monitor.s

# target to generate assembly for a file
src/keyboard_monitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/keyboard_monitor.cpp.s
.PHONY : src/keyboard_monitor.cpp.s

src/logic.o: src/logic.cpp.o
.PHONY : src/logic.o

# target to build an object file
src/logic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/logic.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_fix.dir/build.make CMakeFiles/test_ballistics_fix.dir/src/logic.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_actual.dir/build.make CMakeFiles/test_ballistics_actual.dir/src/logic.cpp.o
.PHONY : src/logic.cpp.o

src/logic.i: src/logic.cpp.i
.PHONY : src/logic.i

# target to preprocess a source file
src/logic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/logic.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_fix.dir/build.make CMakeFiles/test_ballistics_fix.dir/src/logic.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_actual.dir/build.make CMakeFiles/test_ballistics_actual.dir/src/logic.cpp.i
.PHONY : src/logic.cpp.i

src/logic.s: src/logic.cpp.s
.PHONY : src/logic.s

# target to generate assembly for a file
src/logic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/logic.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_fix.dir/build.make CMakeFiles/test_ballistics_fix.dir/src/logic.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_actual.dir/build.make CMakeFiles/test_ballistics_actual.dir/src/logic.cpp.s
.PHONY : src/logic.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/orientation_sensor.o: src/orientation_sensor.cpp.o
.PHONY : src/orientation_sensor.o

# target to build an object file
src/orientation_sensor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/orientation_sensor.cpp.o
.PHONY : src/orientation_sensor.cpp.o

src/orientation_sensor.i: src/orientation_sensor.cpp.i
.PHONY : src/orientation_sensor.i

# target to preprocess a source file
src/orientation_sensor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/orientation_sensor.cpp.i
.PHONY : src/orientation_sensor.cpp.i

src/orientation_sensor.s: src/orientation_sensor.cpp.s
.PHONY : src/orientation_sensor.s

# target to generate assembly for a file
src/orientation_sensor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/orientation_sensor.cpp.s
.PHONY : src/orientation_sensor.cpp.s

src/pca9685_controller.o: src/pca9685_controller.cpp.o
.PHONY : src/pca9685_controller.o

# target to build an object file
src/pca9685_controller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/pca9685_controller.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/servo_test.dir/build.make CMakeFiles/servo_test.dir/src/pca9685_controller.cpp.o
.PHONY : src/pca9685_controller.cpp.o

src/pca9685_controller.i: src/pca9685_controller.cpp.i
.PHONY : src/pca9685_controller.i

# target to preprocess a source file
src/pca9685_controller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/pca9685_controller.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/servo_test.dir/build.make CMakeFiles/servo_test.dir/src/pca9685_controller.cpp.i
.PHONY : src/pca9685_controller.cpp.i

src/pca9685_controller.s: src/pca9685_controller.cpp.s
.PHONY : src/pca9685_controller.s

# target to generate assembly for a file
src/pca9685_controller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/pca9685_controller.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/servo_test.dir/build.make CMakeFiles/servo_test.dir/src/pca9685_controller.cpp.s
.PHONY : src/pca9685_controller.cpp.s

src/servo_test.o: src/servo_test.cpp.o
.PHONY : src/servo_test.o

# target to build an object file
src/servo_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/servo_test.dir/build.make CMakeFiles/servo_test.dir/src/servo_test.cpp.o
.PHONY : src/servo_test.cpp.o

src/servo_test.i: src/servo_test.cpp.i
.PHONY : src/servo_test.i

# target to preprocess a source file
src/servo_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/servo_test.dir/build.make CMakeFiles/servo_test.dir/src/servo_test.cpp.i
.PHONY : src/servo_test.cpp.i

src/servo_test.s: src/servo_test.cpp.s
.PHONY : src/servo_test.s

# target to generate assembly for a file
src/servo_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/servo_test.dir/build.make CMakeFiles/servo_test.dir/src/servo_test.cpp.s
.PHONY : src/servo_test.cpp.s

src/system_monitor.o: src/system_monitor.cpp.o
.PHONY : src/system_monitor.o

# target to build an object file
src/system_monitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/system_monitor.cpp.o
.PHONY : src/system_monitor.cpp.o

src/system_monitor.i: src/system_monitor.cpp.i
.PHONY : src/system_monitor.i

# target to preprocess a source file
src/system_monitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/system_monitor.cpp.i
.PHONY : src/system_monitor.cpp.i

src/system_monitor.s: src/system_monitor.cpp.s
.PHONY : src/system_monitor.s

# target to generate assembly for a file
src/system_monitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/system_monitor.cpp.s
.PHONY : src/system_monitor.cpp.s

src/util_logging.o: src/util_logging.cpp.o
.PHONY : src/util_logging.o

# target to build an object file
src/util_logging.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/util_logging.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_loader_test.dir/build.make CMakeFiles/config_loader_test.dir/src/util_logging.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/servo_test.dir/build.make CMakeFiles/servo_test.dir/src/util_logging.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/src/util_logging.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_fix.dir/build.make CMakeFiles/test_ballistics_fix.dir/src/util_logging.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_actual.dir/build.make CMakeFiles/test_ballistics_actual.dir/src/util_logging.cpp.o
.PHONY : src/util_logging.cpp.o

src/util_logging.i: src/util_logging.cpp.i
.PHONY : src/util_logging.i

# target to preprocess a source file
src/util_logging.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/util_logging.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_loader_test.dir/build.make CMakeFiles/config_loader_test.dir/src/util_logging.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/servo_test.dir/build.make CMakeFiles/servo_test.dir/src/util_logging.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/src/util_logging.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_fix.dir/build.make CMakeFiles/test_ballistics_fix.dir/src/util_logging.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_actual.dir/build.make CMakeFiles/test_ballistics_actual.dir/src/util_logging.cpp.i
.PHONY : src/util_logging.cpp.i

src/util_logging.s: src/util_logging.cpp.s
.PHONY : src/util_logging.s

# target to generate assembly for a file
src/util_logging.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/util_logging.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_loader_test.dir/build.make CMakeFiles/config_loader_test.dir/src/util_logging.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/servo_test.dir/build.make CMakeFiles/servo_test.dir/src/util_logging.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/src/util_logging.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_fix.dir/build.make CMakeFiles/test_ballistics_fix.dir/src/util_logging.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_actual.dir/build.make CMakeFiles/test_ballistics_actual.dir/src/util_logging.cpp.s
.PHONY : src/util_logging.cpp.s

test_ballistics_actual.o: test_ballistics_actual.cpp.o
.PHONY : test_ballistics_actual.o

# target to build an object file
test_ballistics_actual.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_actual.dir/build.make CMakeFiles/test_ballistics_actual.dir/test_ballistics_actual.cpp.o
.PHONY : test_ballistics_actual.cpp.o

test_ballistics_actual.i: test_ballistics_actual.cpp.i
.PHONY : test_ballistics_actual.i

# target to preprocess a source file
test_ballistics_actual.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_actual.dir/build.make CMakeFiles/test_ballistics_actual.dir/test_ballistics_actual.cpp.i
.PHONY : test_ballistics_actual.cpp.i

test_ballistics_actual.s: test_ballistics_actual.cpp.s
.PHONY : test_ballistics_actual.s

# target to generate assembly for a file
test_ballistics_actual.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_actual.dir/build.make CMakeFiles/test_ballistics_actual.dir/test_ballistics_actual.cpp.s
.PHONY : test_ballistics_actual.cpp.s

test_ballistics_fix.o: test_ballistics_fix.cpp.o
.PHONY : test_ballistics_fix.o

# target to build an object file
test_ballistics_fix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_fix.dir/build.make CMakeFiles/test_ballistics_fix.dir/test_ballistics_fix.cpp.o
.PHONY : test_ballistics_fix.cpp.o

test_ballistics_fix.i: test_ballistics_fix.cpp.i
.PHONY : test_ballistics_fix.i

# target to preprocess a source file
test_ballistics_fix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_fix.dir/build.make CMakeFiles/test_ballistics_fix.dir/test_ballistics_fix.cpp.i
.PHONY : test_ballistics_fix.cpp.i

test_ballistics_fix.s: test_ballistics_fix.cpp.s
.PHONY : test_ballistics_fix.s

# target to generate assembly for a file
test_ballistics_fix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_fix.dir/build.make CMakeFiles/test_ballistics_fix.dir/test_ballistics_fix.cpp.s
.PHONY : test_ballistics_fix.cpp.s

test_ballistics_fixed.o: test_ballistics_fixed.cpp.o
.PHONY : test_ballistics_fixed.o

# target to build an object file
test_ballistics_fixed.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_fixed.dir/build.make CMakeFiles/test_ballistics_fixed.dir/test_ballistics_fixed.cpp.o
.PHONY : test_ballistics_fixed.cpp.o

test_ballistics_fixed.i: test_ballistics_fixed.cpp.i
.PHONY : test_ballistics_fixed.i

# target to preprocess a source file
test_ballistics_fixed.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_fixed.dir/build.make CMakeFiles/test_ballistics_fixed.dir/test_ballistics_fixed.cpp.i
.PHONY : test_ballistics_fixed.cpp.i

test_ballistics_fixed.s: test_ballistics_fixed.cpp.s
.PHONY : test_ballistics_fixed.s

# target to generate assembly for a file
test_ballistics_fixed.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_fixed.dir/build.make CMakeFiles/test_ballistics_fixed.dir/test_ballistics_fixed.cpp.s
.PHONY : test_ballistics_fixed.cpp.s

test_ballistics_simple.o: test_ballistics_simple.cpp.o
.PHONY : test_ballistics_simple.o

# target to build an object file
test_ballistics_simple.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_simple.dir/build.make CMakeFiles/test_ballistics_simple.dir/test_ballistics_simple.cpp.o
.PHONY : test_ballistics_simple.cpp.o

test_ballistics_simple.i: test_ballistics_simple.cpp.i
.PHONY : test_ballistics_simple.i

# target to preprocess a source file
test_ballistics_simple.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_simple.dir/build.make CMakeFiles/test_ballistics_simple.dir/test_ballistics_simple.cpp.i
.PHONY : test_ballistics_simple.cpp.i

test_ballistics_simple.s: test_ballistics_simple.cpp.s
.PHONY : test_ballistics_simple.s

# target to generate assembly for a file
test_ballistics_simple.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ballistics_simple.dir/build.make CMakeFiles/test_ballistics_simple.dir/test_ballistics_simple.cpp.s
.PHONY : test_ballistics_simple.cpp.s

test_config.o: test_config.cpp.o
.PHONY : test_config.o

# target to build an object file
test_config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/test_config.cpp.o
.PHONY : test_config.cpp.o

test_config.i: test_config.cpp.i
.PHONY : test_config.i

# target to preprocess a source file
test_config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/test_config.cpp.i
.PHONY : test_config.cpp.i

test_config.s: test_config.cpp.s
.PHONY : test_config.s

# target to generate assembly for a file
test_config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/test_config.cpp.s
.PHONY : test_config.cpp.s

test_tensor_access.o: test_tensor_access.cpp.o
.PHONY : test_tensor_access.o

# target to build an object file
test_tensor_access.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tensor_access.dir/build.make CMakeFiles/test_tensor_access.dir/test_tensor_access.cpp.o
.PHONY : test_tensor_access.cpp.o

test_tensor_access.i: test_tensor_access.cpp.i
.PHONY : test_tensor_access.i

# target to preprocess a source file
test_tensor_access.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tensor_access.dir/build.make CMakeFiles/test_tensor_access.dir/test_tensor_access.cpp.i
.PHONY : test_tensor_access.cpp.i

test_tensor_access.s: test_tensor_access.cpp.s
.PHONY : test_tensor_access.s

# target to generate assembly for a file
test_tensor_access.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tensor_access.dir/build.make CMakeFiles/test_tensor_access.dir/test_tensor_access.cpp.s
.PHONY : test_tensor_access.cpp.s

tests/config_loader_test.o: tests/config_loader_test.cpp.o
.PHONY : tests/config_loader_test.o

# target to build an object file
tests/config_loader_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_loader_test.dir/build.make CMakeFiles/config_loader_test.dir/tests/config_loader_test.cpp.o
.PHONY : tests/config_loader_test.cpp.o

tests/config_loader_test.i: tests/config_loader_test.cpp.i
.PHONY : tests/config_loader_test.i

# target to preprocess a source file
tests/config_loader_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_loader_test.dir/build.make CMakeFiles/config_loader_test.dir/tests/config_loader_test.cpp.i
.PHONY : tests/config_loader_test.cpp.i

tests/config_loader_test.s: tests/config_loader_test.cpp.s
.PHONY : tests/config_loader_test.s

# target to generate assembly for a file
tests/config_loader_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_loader_test.dir/build.make CMakeFiles/config_loader_test.dir/tests/config_loader_test.cpp.s
.PHONY : tests/config_loader_test.cpp.s

tests/dlopen_test.o: tests/dlopen_test.cpp.o
.PHONY : tests/dlopen_test.o

# target to build an object file
tests/dlopen_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlopen_test.dir/build.make CMakeFiles/dlopen_test.dir/tests/dlopen_test.cpp.o
.PHONY : tests/dlopen_test.cpp.o

tests/dlopen_test.i: tests/dlopen_test.cpp.i
.PHONY : tests/dlopen_test.i

# target to preprocess a source file
tests/dlopen_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlopen_test.dir/build.make CMakeFiles/dlopen_test.dir/tests/dlopen_test.cpp.i
.PHONY : tests/dlopen_test.cpp.i

tests/dlopen_test.s: tests/dlopen_test.cpp.s
.PHONY : tests/dlopen_test.s

# target to generate assembly for a file
tests/dlopen_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlopen_test.dir/build.make CMakeFiles/dlopen_test.dir/tests/dlopen_test.cpp.s
.PHONY : tests/dlopen_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... config_loader_test"
	@echo "... detector"
	@echo "... dlopen_test"
	@echo "... inspect_model_tensors"
	@echo "... minimal_model_test"
	@echo "... servo_test"
	@echo "... test_ballistics_actual"
	@echo "... test_ballistics_fix"
	@echo "... test_ballistics_fixed"
	@echo "... test_ballistics_simple"
	@echo "... test_config"
	@echo "... test_tensor_access"
	@echo "... civetweb/src/civetweb.o"
	@echo "... civetweb/src/civetweb.i"
	@echo "... civetweb/src/civetweb.s"
	@echo "... inspect_model_tensors.o"
	@echo "... inspect_model_tensors.i"
	@echo "... inspect_model_tensors.s"
	@echo "... minimal_model_test.o"
	@echo "... minimal_model_test.i"
	@echo "... minimal_model_test.s"
	@echo "... src/application.o"
	@echo "... src/application.i"
	@echo "... src/application.s"
	@echo "... src/application_supervisor.o"
	@echo "... src/application_supervisor.i"
	@echo "... src/application_supervisor.s"
	@echo "... src/camera_capture.o"
	@echo "... src/camera_capture.i"
	@echo "... src/camera_capture.s"
	@echo "... src/config_loader.o"
	@echo "... src/config_loader.i"
	@echo "... src/config_loader.s"
	@echo "... src/h264_encoder.o"
	@echo "... src/h264_encoder.i"
	@echo "... src/h264_encoder.s"
	@echo "... src/image_processor.o"
	@echo "... src/image_processor.i"
	@echo "... src/image_processor.s"
	@echo "... src/inference.o"
	@echo "... src/inference.i"
	@echo "... src/inference.s"
	@echo "... src/keyboard_monitor.o"
	@echo "... src/keyboard_monitor.i"
	@echo "... src/keyboard_monitor.s"
	@echo "... src/logic.o"
	@echo "... src/logic.i"
	@echo "... src/logic.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/orientation_sensor.o"
	@echo "... src/orientation_sensor.i"
	@echo "... src/orientation_sensor.s"
	@echo "... src/pca9685_controller.o"
	@echo "... src/pca9685_controller.i"
	@echo "... src/pca9685_controller.s"
	@echo "... src/servo_test.o"
	@echo "... src/servo_test.i"
	@echo "... src/servo_test.s"
	@echo "... src/system_monitor.o"
	@echo "... src/system_monitor.i"
	@echo "... src/system_monitor.s"
	@echo "... src/util_logging.o"
	@echo "... src/util_logging.i"
	@echo "... src/util_logging.s"
	@echo "... test_ballistics_actual.o"
	@echo "... test_ballistics_actual.i"
	@echo "... test_ballistics_actual.s"
	@echo "... test_ballistics_fix.o"
	@echo "... test_ballistics_fix.i"
	@echo "... test_ballistics_fix.s"
	@echo "... test_ballistics_fixed.o"
	@echo "... test_ballistics_fixed.i"
	@echo "... test_ballistics_fixed.s"
	@echo "... test_ballistics_simple.o"
	@echo "... test_ballistics_simple.i"
	@echo "... test_ballistics_simple.s"
	@echo "... test_config.o"
	@echo "... test_config.i"
	@echo "... test_config.s"
	@echo "... test_tensor_access.o"
	@echo "... test_tensor_access.i"
	@echo "... test_tensor_access.s"
	@echo "... tests/config_loader_test.o"
	@echo "... tests/config_loader_test.i"
	@echo "... tests/config_loader_test.s"
	@echo "... tests/dlopen_test.o"
	@echo "... tests/dlopen_test.i"
	@echo "... tests/dlopen_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

