# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/CoralEdgeTpu

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/CoralEdgeTpu

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/CoralEdgeTpu/CMakeFiles /home/pi/CoralEdgeTpu//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/CoralEdgeTpu/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named detector

# Build rule for target.
detector: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 detector
.PHONY : detector

# fast build rule for target.
detector/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/build
.PHONY : detector/fast

src/camera_capture.o: src/camera_capture.cpp.o
.PHONY : src/camera_capture.o

# target to build an object file
src/camera_capture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/camera_capture.cpp.o
.PHONY : src/camera_capture.cpp.o

src/camera_capture.i: src/camera_capture.cpp.i
.PHONY : src/camera_capture.i

# target to preprocess a source file
src/camera_capture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/camera_capture.cpp.i
.PHONY : src/camera_capture.cpp.i

src/camera_capture.s: src/camera_capture.cpp.s
.PHONY : src/camera_capture.s

# target to generate assembly for a file
src/camera_capture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/camera_capture.cpp.s
.PHONY : src/camera_capture.cpp.s

src/inference.o: src/inference.cpp.o
.PHONY : src/inference.o

# target to build an object file
src/inference.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/inference.cpp.o
.PHONY : src/inference.cpp.o

src/inference.i: src/inference.cpp.i
.PHONY : src/inference.i

# target to preprocess a source file
src/inference.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/inference.cpp.i
.PHONY : src/inference.cpp.i

src/inference.s: src/inference.cpp.s
.PHONY : src/inference.s

# target to generate assembly for a file
src/inference.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/inference.cpp.s
.PHONY : src/inference.cpp.s

src/jpeg_wrapper.o: src/jpeg_wrapper.cpp.o
.PHONY : src/jpeg_wrapper.o

# target to build an object file
src/jpeg_wrapper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/jpeg_wrapper.cpp.o
.PHONY : src/jpeg_wrapper.cpp.o

src/jpeg_wrapper.i: src/jpeg_wrapper.cpp.i
.PHONY : src/jpeg_wrapper.i

# target to preprocess a source file
src/jpeg_wrapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/jpeg_wrapper.cpp.i
.PHONY : src/jpeg_wrapper.cpp.i

src/jpeg_wrapper.s: src/jpeg_wrapper.cpp.s
.PHONY : src/jpeg_wrapper.s

# target to generate assembly for a file
src/jpeg_wrapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/jpeg_wrapper.cpp.s
.PHONY : src/jpeg_wrapper.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mjpeg_server.o: src/mjpeg_server.cpp.o
.PHONY : src/mjpeg_server.o

# target to build an object file
src/mjpeg_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/mjpeg_server.cpp.o
.PHONY : src/mjpeg_server.cpp.o

src/mjpeg_server.i: src/mjpeg_server.cpp.i
.PHONY : src/mjpeg_server.i

# target to preprocess a source file
src/mjpeg_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/mjpeg_server.cpp.i
.PHONY : src/mjpeg_server.cpp.i

src/mjpeg_server.s: src/mjpeg_server.cpp.s
.PHONY : src/mjpeg_server.s

# target to generate assembly for a file
src/mjpeg_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/mjpeg_server.cpp.s
.PHONY : src/mjpeg_server.cpp.s

src/udp_sender.o: src/udp_sender.cpp.o
.PHONY : src/udp_sender.o

# target to build an object file
src/udp_sender.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/udp_sender.cpp.o
.PHONY : src/udp_sender.cpp.o

src/udp_sender.i: src/udp_sender.cpp.i
.PHONY : src/udp_sender.i

# target to preprocess a source file
src/udp_sender.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/udp_sender.cpp.i
.PHONY : src/udp_sender.cpp.i

src/udp_sender.s: src/udp_sender.cpp.s
.PHONY : src/udp_sender.s

# target to generate assembly for a file
src/udp_sender.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/udp_sender.cpp.s
.PHONY : src/udp_sender.cpp.s

src/util_logging.o: src/util_logging.cpp.o
.PHONY : src/util_logging.o

# target to build an object file
src/util_logging.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/util_logging.cpp.o
.PHONY : src/util_logging.cpp.o

src/util_logging.i: src/util_logging.cpp.i
.PHONY : src/util_logging.i

# target to preprocess a source file
src/util_logging.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/util_logging.cpp.i
.PHONY : src/util_logging.cpp.i

src/util_logging.s: src/util_logging.cpp.s
.PHONY : src/util_logging.s

# target to generate assembly for a file
src/util_logging.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detector.dir/build.make CMakeFiles/detector.dir/src/util_logging.cpp.s
.PHONY : src/util_logging.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... detector"
	@echo "... src/camera_capture.o"
	@echo "... src/camera_capture.i"
	@echo "... src/camera_capture.s"
	@echo "... src/inference.o"
	@echo "... src/inference.i"
	@echo "... src/inference.s"
	@echo "... src/jpeg_wrapper.o"
	@echo "... src/jpeg_wrapper.i"
	@echo "... src/jpeg_wrapper.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mjpeg_server.o"
	@echo "... src/mjpeg_server.i"
	@echo "... src/mjpeg_server.s"
	@echo "... src/udp_sender.o"
	@echo "... src/udp_sender.i"
	@echo "... src/udp_sender.s"
	@echo "... src/util_logging.o"
	@echo "... src/util_logging.i"
	@echo "... src/util_logging.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

